---
input:
  type: RosInput
  tf_verbosity: 1
  clear_queue_on_fail: true
  tf_lookup:
    wait_duration_s: 1   
    buffer_size_s: 60.0     
    max_tries: 10           
    verbosity: 3            
  inputs:
    left_cam:
      receiver:
        type: ClosedSetImageReceiver
      sensor:
        type: camera_info
        min_range: 0.2
        max_range: 5.0
        extrinsics:
          type: ros
          sensor_frame: $(arg sensor_frame)
